name = "matters-fediverse-gateway-demo"
main = "src/index.js"
compatibility_date = "2026-04-30"
account_id = "757aaed316df635d8deb63859258808c"
workers_dev = true

[[routes]]
pattern = "gateway-demo.matters.town"
custom_domain = true

[[routes]]
pattern = "matters.town/.well-known/webfinger*"
zone_name = "matters.town"

[[routes]]
pattern = "matters.town/.well-known/host-meta"
zone_name = "matters.town"

[[routes]]
pattern = "matters.town/.well-known/nodeinfo"
zone_name = "matters.town"

[[routes]]
pattern = "matters.town/nodeinfo/*"
zone_name = "matters.town"

[[routes]]
pattern = "matters.town/ap/*"
zone_name = "matters.town"

[vars]
MATTERS_PROFILE_URL = "https://matters.town"
PROJECT_DOCS_URL = "https://thematters.github.io/matters-fediverse-gateway/"
